{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "vector-rag.labels" . | nindent 4 }}
    istio-injection: enabled
{{- end }}
