{{- range $k, $svc := .Values.services }}
{{- if and $svc.enabled (hasKey $svc "autoscaling") $svc.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ $svc.name }}
  labels:
    {{- include "sahool.labels" $ | nindent 4 }}
    sahool/service: {{ $svc.name }}
spec:
  scaleTargetRef:
    apiVersion: {{- if and $.Values.rollouts.enabled (default true $svc.rollout.enabled) -}} argoproj.io/v1alpha1 {{- else -}} apps/v1 {{- end }}
    kind: {{- if and $.Values.rollouts.enabled (default true $svc.rollout.enabled) -}} Rollout {{- else -}} Deployment {{- end }}
    name: {{ $.Release.Name }}-{{ $svc.name }}
  minReplicas: {{ default 2 $svc.autoscaling.minReplicas }}
  maxReplicas: {{ default 10 $svc.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 70 $svc.autoscaling.targetCPUUtilizationPercentage }}
{{- if $svc.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $svc.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
---
{{- end }}
{{- end }}
