apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sahool.fullname" . }}-secrets
  labels:
    {{- include "sahool.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.security.jwt.secretKey | default (randAlphaNum 64) | b64enc | quote }}
