{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sahool.serviceAccountName" . }}
  labels:
    {{- include "sahool.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
{{- if .Values.security.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sahool.fullname" . }}
  labels:
    {{- include "sahool.labels" . | nindent 4 }}
rules:
  {{- with .Values.security.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sahool.fullname" . }}
  labels:
    {{- include "sahool.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sahool.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sahool.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
